<script lang="ts" setup>
</script>
<template>
  <table class="data-table">
    <thead>
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Role</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>1</td>
        <td>Alice</td>
        <td>Developer</td>
      </tr>
      <tr>
        <td>2</td>
        <td>Bob</td>
        <td>Designer</td>
      </tr>
      <tr>
        <td>3</td>
        <td>Charlie</td>
        <td>Manager</td>
      </tr>
    </tbody>
  </table>
</template>